// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2rC67HkcF82pDkoMooemMkPF064sZVCs',
    appId: '1:846224573801:web:9176a5cc8a821dcfdc29f8',
    messagingSenderId: '846224573801',
    projectId: 'project-pam-9f37e',
    authDomain: 'project-pam-9f37e.firebaseapp.com',
    storageBucket: 'project-pam-9f37e.firebasestorage.app',
    measurementId: 'G-3P1E3VM66R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpjWGRtDXpMaWEamUr2_DaX_C30EmUPJQ',
    appId: '1:846224573801:android:bc8f788ecf6c93fadc29f8',
    messagingSenderId: '846224573801',
    projectId: 'project-pam-9f37e',
    storageBucket: 'project-pam-9f37e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVukHCzCl83fzNEkeqi_LVfr6D_13_hgs',
    appId: '1:846224573801:ios:bd44b1f19b44462bdc29f8',
    messagingSenderId: '846224573801',
    projectId: 'project-pam-9f37e',
    storageBucket: 'project-pam-9f37e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVukHCzCl83fzNEkeqi_LVfr6D_13_hgs',
    appId: '1:846224573801:ios:bd44b1f19b44462bdc29f8',
    messagingSenderId: '846224573801',
    projectId: 'project-pam-9f37e',
    storageBucket: 'project-pam-9f37e.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2rC67HkcF82pDkoMooemMkPF064sZVCs',
    appId: '1:846224573801:web:476062ebcc1dcaebdc29f8',
    messagingSenderId: '846224573801',
    projectId: 'project-pam-9f37e',
    authDomain: 'project-pam-9f37e.firebaseapp.com',
    storageBucket: 'project-pam-9f37e.firebasestorage.app',
    measurementId: 'G-473JVL6KJV',
  );

}